// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Server struct {
	ID              uuid.UUID
	CanonicalOrigin string
	IsLocal         bool
	CreatedAt       time.Time
}
