// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (canonical_origin, is_local)
VALUES ($1, $2)
RETURNING id, canonical_origin, is_local, created_at
`

type CreateServerParams struct {
	CanonicalOrigin string
	IsLocal         bool
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer, arg.CanonicalOrigin, arg.IsLocal)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.CanonicalOrigin,
		&i.IsLocal,
		&i.CreatedAt,
	)
	return i, err
}

const getLocalServer = `-- name: GetLocalServer :one
SELECT id, canonical_origin, is_local, created_at FROM servers
WHERE is_local
`

func (q *Queries) GetLocalServer(ctx context.Context) (Server, error) {
	row := q.db.QueryRow(ctx, getLocalServer)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.CanonicalOrigin,
		&i.IsLocal,
		&i.CreatedAt,
	)
	return i, err
}

const insertLocalServerIfAbsent = `-- name: InsertLocalServerIfAbsent :exec
INSERT INTO servers (canonical_origin, is_local)
VALUES ($1, true)
ON CONFLICT (is_local) WHERE is_local DO NOTHING
`

// Races between concurrent starts are settled by the servers_single_local index.
func (q *Queries) InsertLocalServerIfAbsent(ctx context.Context, canonicalOrigin string) error {
	_, err := q.db.Exec(ctx, insertLocalServerIfAbsent, canonicalOrigin)
	return err
}
