// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (id, home_server_id, canonical_url, username)
VALUES ($1, $2, $3, $4)
RETURNING id, home_server_id, canonical_url, username, display_name, status, created_at, updated_at
`

type InsertAccountParams struct {
	ID           uuid.UUID
	HomeServerID uuid.UUID
	CanonicalUrl string
	Username     string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.ID,
		arg.HomeServerID,
		arg.CanonicalUrl,
		arg.Username,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.HomeServerID,
		&i.CanonicalUrl,
		&i.Username,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocalAccount = `-- name: InsertLocalAccount :one
INSERT INTO local_accounts (account_id, email, password_hash, server_role)
VALUES ($1, $2, $3, $4)
RETURNING account_id, email, email_verified_at, password_hash, server_role, created_at, updated_at
`

type InsertLocalAccountParams struct {
	AccountID    uuid.UUID
	Email        string
	PasswordHash string
	ServerRole   string
}

func (q *Queries) InsertLocalAccount(ctx context.Context, arg InsertLocalAccountParams) (LocalAccount, error) {
	row := q.db.QueryRow(ctx, insertLocalAccount,
		arg.AccountID,
		arg.Email,
		arg.PasswordHash,
		arg.ServerRole,
	)
	var i LocalAccount
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.ServerRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
