// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID           uuid.UUID
	HomeServerID uuid.UUID
	CanonicalUrl string
	Username     string
	DisplayName  *string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Job struct {
	ID           uuid.UUID
	Kind         string
	Payload      []byte
	Status       string
	Attempts     int32
	MaxAttempts  int32
	LeaseSeconds int32
	Sensitive    bool
	RunAfter     time.Time
	LeaseUntil   *time.Time
	LastError    *string
	FailedAt     *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type LocalAccount struct {
	AccountID       uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	PasswordHash    string
	ServerRole      string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Server struct {
	ID              uuid.UUID
	CanonicalOrigin string
	IsLocal         bool
	CreatedAt       time.Time
}
