// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimJobs = `-- name: ClaimJobs :many
UPDATE jobs
SET status      = 'running',
    attempts    = attempts + 1,
    lease_until = now() + make_interval(secs => lease_seconds),
    updated_at  = now()
WHERE id IN (
    SELECT id FROM jobs
    WHERE attempts < max_attempts
      AND ((status = 'pending' AND run_after <= now())
        OR (status = 'running' AND lease_until < now()))
    ORDER BY run_after, id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, payload, attempts, max_attempts, lease_seconds
`

type ClaimJobsRow struct {
	ID           uuid.UUID
	Kind         string
	Payload      []byte
	Attempts     int32
	MaxAttempts  int32
	LeaseSeconds int32
}

// Claims up to max_jobs runnable jobs: pending ones that are due, and running
// ones whose lease expired (their worker died). SKIP LOCKED lets concurrent
// workers claim different jobs instead of waiting on each other.
func (q *Queries) ClaimJobs(ctx context.Context, maxJobs int32) ([]ClaimJobsRow, error) {
	rows, err := q.db.Query(ctx, claimJobs, maxJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimJobsRow
	for rows.Next() {
		var i ClaimJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LeaseSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeJob = `-- name: CompleteJob :execrows
DELETE FROM jobs
WHERE id = $1 AND status = 'running' AND attempts = $2
`

type CompleteJobParams struct {
	ID       uuid.UUID
	Attempts int32
}

// Only the attempt that still holds the job may record its outcome.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredFailedJobs = `-- name: DeleteExpiredFailedJobs :execrows
DELETE FROM jobs
WHERE status = 'failed' AND failed_at < now() - interval '14 days'
`

func (q *Queries) DeleteExpiredFailedJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredFailedJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failAbandonedJobs = `-- name: FailAbandonedJobs :execrows
UPDATE jobs
SET status      = 'failed',
    lease_until = NULL,
    failed_at   = now(),
    last_error  = 'lease expired during the final attempt',
    payload     = CASE WHEN sensitive THEN NULL ELSE payload END,
    updated_at  = now()
WHERE status = 'running' AND lease_until < now() AND attempts >= max_attempts
`

// Final attempts whose worker vanished: the lease expired and no attempts remain.
func (q *Queries) FailAbandonedJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failAbandonedJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failJob = `-- name: FailJob :execrows
UPDATE jobs
SET status      = 'failed',
    lease_until = NULL,
    failed_at   = now(),
    last_error  = $1,
    payload     = CASE WHEN sensitive THEN NULL ELSE payload END,
    updated_at  = now()
WHERE id = $2 AND status = 'running' AND attempts = $3
`

type FailJobParams struct {
	LastError *string
	ID        uuid.UUID
	Attempts  int32
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJob, arg.LastError, arg.ID, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (kind, payload, max_attempts, lease_seconds, sensitive)
VALUES ($1, $2, $3, $4, $5)
`

type InsertJobParams struct {
	Kind         string
	Payload      []byte
	MaxAttempts  int32
	LeaseSeconds int32
	Sensitive    bool
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob,
		arg.Kind,
		arg.Payload,
		arg.MaxAttempts,
		arg.LeaseSeconds,
		arg.Sensitive,
	)
	return err
}

const jobCounts = `-- name: JobCounts :many
SELECT kind, status, count(*)::integer AS jobs
FROM jobs
GROUP BY kind, status
ORDER BY kind, status
`

type JobCountsRow struct {
	Kind   string
	Status string
	Jobs   int32
}

func (q *Queries) JobCounts(ctx context.Context) ([]JobCountsRow, error) {
	rows, err := q.db.Query(ctx, jobCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobCountsRow
	for rows.Next() {
		var i JobCountsRow
		if err := rows.Scan(&i.Kind, &i.Status, &i.Jobs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestOverdueJobSeconds = `-- name: OldestOverdueJobSeconds :one
SELECT coalesce(extract(epoch FROM now() - min(run_after)), 0)::float8 AS overdue_seconds
FROM jobs
WHERE status = 'pending' AND run_after <= now()
`

// How late the most overdue runnable job is, in seconds; 0 when nothing waits.
func (q *Queries) OldestOverdueJobSeconds(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, oldestOverdueJobSeconds)
	var overdue_seconds float64
	err := row.Scan(&overdue_seconds)
	return overdue_seconds, err
}

const recentFailedJobs = `-- name: RecentFailedJobs :many
SELECT id, kind, attempts, last_error, failed_at
FROM jobs
WHERE status = 'failed'
ORDER BY failed_at DESC
LIMIT 10
`

type RecentFailedJobsRow struct {
	ID        uuid.UUID
	Kind      string
	Attempts  int32
	LastError *string
	FailedAt  *time.Time
}

func (q *Queries) RecentFailedJobs(ctx context.Context) ([]RecentFailedJobsRow, error) {
	rows, err := q.db.Query(ctx, recentFailedJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentFailedJobsRow
	for rows.Next() {
		var i RecentFailedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Attempts,
			&i.LastError,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET status      = 'pending',
    lease_until = NULL,
    run_after   = now() + make_interval(secs => $1::float8),
    last_error  = $2,
    updated_at  = now()
WHERE id = $3 AND status = 'running' AND attempts = $4
`

type RetryJobParams struct {
	DelaySeconds float64
	LastError    *string
	ID           uuid.UUID
	Attempts     int32
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.DelaySeconds,
		arg.LastError,
		arg.ID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
